version: '3.8'
services:
  wire-pod:
    image: ghcr.io/zippy-boy/wire-pod:main
    restart: unless-stopped
    ports:
      - 443:443
      - 8080:8080
      - 80:80
      - 8084:8084
    volumes:
      - wire-pod-data:/app/chipper/
      - wire-pod-model:/app/vosk/
volumes:
  wire-pod-data:
    driver: local
  wire-pod-model:
    driver: local
